// <auto-generated />
using System;
using JobApiApp.JobApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobApi.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("JobApiApp.JobApi.Models.JobPosition", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobTitleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("ParentId");

                    b.ToTable("JobPositions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0190ee35-367b-712b-9454-5e82dcd9de07"),
                            Code = "101",
                            Description = "BackEnd",
                            JobTitleId = new Guid("0190e8dd-0225-725f-8099-93fb2b33a906")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-712c-a960-4e6eeab84c67"),
                            Code = "102",
                            Description = "BackEnd",
                            JobTitleId = new Guid("0190e8dd-0225-7260-800e-9118cdb9d783")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-712d-8b56-ef01144c8ea8"),
                            Code = "103",
                            Description = "BackEnd",
                            JobTitleId = new Guid("0190e8dd-0225-7261-ae42-f896cde1f13b")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-712e-9910-cbc19415d184"),
                            Code = "201",
                            Description = "FrontEnd",
                            JobTitleId = new Guid("0190e8dd-0225-725f-8099-93fb2b33a906")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-712f-9b04-a67110923043"),
                            Code = "202",
                            Description = "FrontEnd",
                            JobTitleId = new Guid("0190e8dd-0225-7260-800e-9118cdb9d783")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-7130-8d57-a015be40a3b0"),
                            Code = "203",
                            Description = "FrontEnd",
                            JobTitleId = new Guid("0190e8dd-0225-7261-ae42-f896cde1f13b")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-7131-a1cc-db680ebe30ee"),
                            Code = "301",
                            Description = "FullStack",
                            JobTitleId = new Guid("0190e8dd-0225-725f-8099-93fb2b33a906")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-7132-894e-627a49786576"),
                            Code = "302",
                            Description = "FullStack",
                            JobTitleId = new Guid("0190e8dd-0225-7260-800e-9118cdb9d783")
                        },
                        new
                        {
                            Id = new Guid("0190ee35-367b-7133-958c-d4e8536d528d"),
                            Code = "303",
                            Description = "FullStack",
                            JobTitleId = new Guid("0190e8dd-0225-7261-ae42-f896cde1f13b")
                        });
                });

            modelBuilder.Entity("JobApiApp.JobApi.Models.JobTitle", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0190e8dd-0225-725f-8099-93fb2b33a906"),
                            Code = "123",
                            Description = "Junior",
                            Level = 1
                        },
                        new
                        {
                            Id = new Guid("0190e8dd-0225-7260-800e-9118cdb9d783"),
                            Code = "100",
                            Description = "Senior",
                            Level = 2
                        },
                        new
                        {
                            Id = new Guid("0190e8dd-0225-7261-ae42-f896cde1f13b"),
                            Code = "200",
                            Description = "Lead",
                            Level = 3
                        });
                });

            modelBuilder.Entity("JobApiApp.JobApi.Models.JobPosition", b =>
                {
                    b.HasOne("JobApiApp.JobApi.Models.JobTitle", "JobTitle")
                        .WithMany("JobPositions")
                        .HasForeignKey("JobTitleId");

                    b.HasOne("JobApiApp.JobApi.Models.JobPosition", "ParentJobPosition")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("JobTitle");

                    b.Navigation("ParentJobPosition");
                });

            modelBuilder.Entity("JobApiApp.JobApi.Models.JobTitle", b =>
                {
                    b.Navigation("JobPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
